### PR TITLE
creating a read me file

### PR DESCRIPTION
**Pull request by xashy-devops**

### CODE REVIEW

**Review by sprck — APPROVED** [review]

**Review by Nes489 — APPROVED** [review]
Looks good

**Review by awomDevOps — APPROVED** [review]

**Review by gadefru — DISMISSED** [review]
this is wishi washy

**Review by aasongwe — APPROVED** [review]
changes accepted

**Review by Emmanuel-code-pod — APPROVED** [review]

**Review by awomDevOps — APPROVED** [review]

**Review by joicedevops — APPROVED** [review]
good

**Review by ManchoHub — APPROVED** [review]

**Review by gadefru — APPROVED** [review]

**Review by saint-OO1 — APPROVED** [review]

**Pull request merged**
